
- name: Adds docker key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: p80.pool.sks-keyservers.net
    state: present
  tags: docker

- name: Adds docker repos
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
    state: present
  tags: docker

- name: Installs docker engine
  apt: pkg=docker-engine state=present
  tags: docker

- name: Installs pip
  apt: name=python-pip state=present
  tags: docker

- name: Installs docker python support
  pip: name=docker-py state=present
  tags: docker
